

set -ga terminal-overrides ",xterm-256color:Tc"
set -g default-terminal "tmux-256color"

unbind r
bind r source-file ~/.tmux.conf

# set -g prefix C-a
# unbind C-b
# bind C-a send-prefix

set -g mouse on

 set -g status-position bottom

# act like vim
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R


# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-sensible'

# themes 

# rose-pine 
# set -g @plugin 'rose-pine/tmux'
# set -g @rose_pine_variant 'main' # main, moon, dawn 

# catppuccin 
set -g @plugin 'catppuccin/tmux#v2.1.3' # See https://github.com/catppuccin/tmux/tags for additional tags 
set -g @catppuccin_flavor 'mocha' # latte, frappe, macchiato or mocha 
set -g @catppuccin_window_status_style "slanted" # basic, rounded, slanted, custom, or none
run ~/.tmux/plugins/tmux/catppuccin.tmux


# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
# set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# Como funciona o tmux (comandos básicos):

# tmux: Inicia uma nova sessão.
# Ctrl+b d (ou Ctrl+a d se você mudou o prefixo): Desanexa da sessão atual (você sai do tmux mas a sessão continua rodando em segundo plano).
# tmux attach: Reconecta à última sessão desanexada.
# tmux attach -t <nome_da_sessao>: Reconecta a uma sessão específica.
# tmux ls: Lista as sessões abertas.
# Ctrl+b %: Divide o painel verticalmente.
# Ctrl+b ": Divide o painel horizontalmente.
# Ctrl+b <setas>: Move entre os painéis.
# Ctrl+b c: Cria uma nova janela.
# Ctrl+b p: Vai para a janela anterior.
# Ctrl+b n: Vai para a próxima janela.
# Ctrl+b 0-9: Vai para a janela com o número correspondente.
# Ctrl+b ,: Renomeia a janela atual.
